name: Build

on:
    pull_request:
        branches:
            - main

    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup python
              uses: actions/setup-python@v3
              with:
                python-version: 3.9
            - name: install dependencies
              run: |
                pip install -r requirements.txt
            # - name: Run server
            #   run: uvicorn app.main:app --reload
            # - name: Run automated tests
            #   run: pytest .
            

